name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rsp:
          - base
          - idfdev
          - idfint
          - idfprod
          - int
          - nts
          - stable
          - summit
          - tucsonteststand

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox
        run: |
          python -m pip install -U pip
          python -m pip install -U tox

      - name: Run tox
        run: tox -e sphinx-${{ matrix.rsp }}
