name: CI

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox
        run: pip install tox

      - name: Run type checking
        run: tox -e typing

      - name: Run precommit hooks
        run: tox -e precommit

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rsp:
          - base
          - idfdev
          - idfint
          - idfprod
          - int
          - nts
          - stable
          - summit
          - tucsonteststand

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox
        run: |
          python -m pip install -U pip
          python -m pip install -U tox

      - name: Run tox
        run: tox -e sphinx-${{ matrix.rsp }}
