name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox
        run: pip install tox

      - name: Run type checking
        run: tox -e typing

      - name: Run precommit hooks
        uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rsp:
          - base
          - idfdev
          - idfint
          - idfprod
          - int
          - nts
          - stable
          - summit

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox
        run: |
          python -m pip install -U pip
          python -m pip install -U tox

      - name: Run tox
        run: tox -e sphinx-${{ matrix.rsp }},linkcheck-${{ matrix.rsp }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.rsp }}
          path: _build/html/${{ matrix.rsp }}/
          if-no-files-found: error

  # For ticket branch previews of the primary environment's docs
  upload-for-branch:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ (github.event_name == 'push') && (github.ref != 'refs/heads/master') }}

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: idfprod
          path: _build/html/idfprod

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install LTD Conveyor
        run: python -m pip install "ltd-conveyor<2.0.0"

      - name: Upload primary
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --gh --dir _build/html/idfprod --product nb


  # For merges to master, run an upload for all environments
  upload-all:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/master') }}

    strategy:
      matrix:
        rsp:
          - base
          - idfdev
          - idfint
          - idfprod
          - int
          - nts
          - stable
          - summit

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.rsp }}
          path: _build/html/${{ matrix.rsp }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install LTD Conveyor
        run: python -m pip install "ltd-conveyor<2.0.0"

      - name: Upload primary
        if: ${{ matrix.rsp == 'idfprod' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --dir _build/html/${{ matrix.rsp }} --product nb --git-ref master

      - name: Upload non-primary
        if: ${{ matrix.rsp != 'idfprod' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --dir _build/html/${{ matrix.rsp }} --product nb --git-ref ${{ matrix.rsp }}
